name: LCM Review Automation

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  review:
    uses: Team-190/.github/.github/workflows/approvalautomation.yaml@main
    secrets:
      APPROVAL_PAT: ${{ secrets.APPROVAL_PAT }}
