# This workflow will build, test, and then publish the Java library.
# It is triggered automatically on every push to the 'main' branch.

name: Build and Publish GompeiLib

on:
  push:
    branches: [ "main" ] # Runs whenever you push to the main branch

jobs:
  # --- JOB 1: BUILD & TEST ---
  # This job runs first to ensure the code compiles and tests pass.
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Run the 'build' task
      # This will compile the code and run any unit tests you have.
      # If this step fails, the workflow will stop.
      - name: Build and Test with Gradle
        run: ./gradlew build

  # --- JOB 2: PUBLISH ---
  # This job only runs if the 'build' job was successful.
  publish:
    # The 'needs' keyword creates the dependency on the 'build' job.
    needs: build
    runs-on: ubuntu-latest

    steps:
      # We still need to check out the code and set up Java in this job.
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run the 'publish' task to upload the library to GitHub Packages.
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          # Your GitHub username or organization name
          GPR_USER: ${{ github.repository_owner }}
          # The Personal Access Token stored as a secret
          GPR_KEY: ${{ secrets.GPR_KEY }}

